# This library requires the export of the variables TEMP and BIN

SOURCE = Source

COMPONENT_OBJECTS_NAME = ComponentObjects
COMPONENT_OBJECTS_DLL = $(BIN)/lib$(COMPONENT_OBJECTS_NAME).dll

All: $(COMPONENT_OBJECTS_DLL)
LOCAL_HEADERS := $(abspath $(wildcard */*.h))

$(COMPONENT_OBJECTS_DLL): $(LOCAL_HEADERS) $(SOURCE)/$(COMPONENT_OBJECTS_NAME).c
	gcc -c -fPIC $(SOURCE)/$(COMPONENT_OBJECTS_NAME).c -o $(TEMP)/$(COMPONENT_OBJECTS_NAME).o
	gcc -shared $(TEMP)/$(COMPONENT_OBJECTS_NAME).o -o $(COMPONENT_OBJECTS_DLL)
